baseURL = 'https://eric-jones/'
languageCode = 'en-us'
title = 'Growing My Life in the Margins'
theme = "hugo-bearblog"

[menu]

[[menu.main]]
  name = "ğŸ¡ Home"
  url = "/"
  weight = 1

[[menu.main]]
  name = "ğŸŒ± Seedlings"
  url = "/seedlings/"
  weight = 2

[[menu.main]]
  name = "ğŸŒ¿ In Bloom"
  url = "/in-bloom/"
  weight = 3

[[menu.main]]
  name = "ğŸŒ¾ Harvest"
  url = "/harvest/"
  weight = 4

[[menu.main]]
  name = "ğŸª± Compost"
  url = "/compost/"
  weight = 5

[[menu.main]]
  name = "ğŸ§ª Lab Log"
  url = "/lab-log/"
  weight = 6

summaryLength = 40

[taxonomies]
  tag = "tags"